name: Android CI Staging

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "develop" ]

jobs:
  build-staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Create Debug Keytore File
        run: echo "${{ secrets.DEBUG_KEY }}" | base64 -d > debug.keystore

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean assembleDebug
